export const locales = ['en', 'pt', 'fr', 'it', 'de'] as const;
export type Locale = (typeof locales)[number];
export const isLocale = (value: string): value is Locale => locales.includes(value as Locale);
export const slugs = ['vanta', 'luzen', 'restaurant-platform'] as const;
export type Project = {
  name: string;
  subtitle?: string;
  typeLabel?: string;
  category: string;
  location?: string;
  description: string;
  challenge: string;
  approach: string;
  solution: string;
  outcome: string;
  highlights: string[];
  sections?: { title: string; text: string }[];
};
export type Content = {
  nav: string[];
  start: string;
  language: string;
  menu: string;
  close: string;
  skip: string;
  eyebrow: string;
  headline: string[];
  intro: string;
  viewWork: string;
  location: string;
  worldwide: string;
  selected: string;
  workIntro: string;
  allWork: string;
  project: string;
  inDevelopment: string;
  independentProduct: string;
  visualNote: string;
  servicesTitle: string;
  servicesIntro: string;
  services: { name: string; text: string; items: string[] }[];
  processTitle: string;
  process: { name: string; text: string }[];
  aboutTitle: string;
  aboutText: string;
  aboutSecond: string;
  founder: string;
  aboutLink: string;
  studio: { statement: string; principlesTitle: string; processLabel: string };
  principles: { name: string; text: string }[];
  capabilities: {
    title: string;
    intro: string;
    groups: { name: string; items: string[] }[];
  };
  contactTitle: string;
  contactIntro: string;
  emailLabel: string;
  footerLine: string;
  elsewhere: string;
  rights: string;
  privacy: string;
  terms: string;
  legalNote: string;
  privacyText: string[];
  termsText: string[];
  caseLabels: string[];
  nextProject: string;
  projects: Project[];
  form: {
    name: string;
    email: string;
    company: string;
    country: string;
    need: string;
    budget: string;
    description: string;
    website: string;
    optional: string;
    select: string;
    other: string;
    unsure: string;
    under: string;
    submit: string;
    sending: string;
    success: string;
    error: string;
    unavailable: string;
    consent: string;
    required: string;
    invalid: string;
    descriptionHint: string;
  };
  notFound: string;
  home: string;
  seo: string;
};
